[package]
name = "tclreadline-wrappers"
version = "2.4.1"
edition = "2021"

build = "build.rs"

[features]
wishrl = []

[lib]
name = "tclreadline"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "tclshrl"
path = "src/bin/tclshrl.rs"

[[bin]]
name = "wishrl"
path = "src/bin/wishrl.rs"
required-features = ["wishrl"]
